export const categoryProfessionalImages = Array.from({ length: 15 }, (_, index) => (
  `/hynt-home/category-professionals/portfolio-${index + 1}.jpeg`
))

export const categoryProfessionals = [
  {
    id: 'rohan-mehta',
    name: 'Rohan Mehta',
    role: 'Interior Designer',
    city: 'Mumbai',
    since: 'Since 2016',
    experience: '8 years',
    rating: '4.8',
    reviews: '210 reviews',
    reviewCount: '210',
    services: '3D Visualization, Commercial Interiors, Residential Interiors, Online Consultation',
    serviceTags: ['Full Home Design', 'Turnkey Execution', '2D Floor Plan', '3D Walkthrough', 'Moodboard', 'Modular Kitchen', 'Vastu-Compliant', 'Site supervision'],
    showroom: 'Shop No. 2, place, at that otherplace',
    hours: '9am - 9pm',
    avatar: '/hynt-home/explore/neha-singh.png',
    images: categoryProfessionalImages.slice(0, 5),
  },
  {
    id: 'aarya-studio',
    name: 'Aarya Design Studio',
    role: 'Interior Designer',
    city: 'Mumbai',
    since: 'Since 2018',
    experience: '6 years',
    rating: '4.7',
    reviews: '168 reviews',
    reviewCount: '168',
    services: 'Residential Interiors, Modular Planning, Renovation Consultation, Styling',
    serviceTags: ['Full Home Design', 'Turnkey Execution', '2D Floor Plan', '3D Walkthrough', 'Moodboard', 'Styling', 'Site supervision'],
    showroom: 'Studio 14, Linking Road, Bandra West',
    hours: '10am - 8pm',
    avatar: '/hynt-home/explore/neha-singh.png',
    images: categoryProfessionalImages.slice(5, 10),
  },
  {
    id: 'neha-singh',
    name: 'Neha Singh',
    role: 'Interior Designer',
    city: 'Mumbai',
    since: 'Since 2016',
    experience: '8 years',
    rating: '4.8',
    reviews: '210 reviews',
    reviewCount: '210',
    services: '3D Visualization, Commercial Interiors, Residential Interiors, Online Consultation',
    serviceTags: ['Full Home Design', 'Turnkey Execution', '2D Floor Plan', '3D Walkthrough', 'Moodboard', 'Modular Kitchen', 'Vastu-Compliant', 'Site supervision'],
    showroom: 'Shop No. 2, place, at that otherplace',
    hours: '9am - 9pm',
    avatar: '/hynt-home/explore/neha-singh.png',
    images: categoryProfessionalImages.slice(10, 15),
  },
]
